/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai6;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Giao_Dien_Tim_Max extends javax.swing.JFrame {

    /**
     * Creates new form Giao_Dien_Tim_Max
     */
    public Giao_Dien_Tim_Max() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        btnSoLonNhat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Số thứ 1");

        jLabel2.setText("Số thứ 2");

        jLabel3.setText("Số thứ 3");

        btnSoLonNhat.setText("Số lớn nhất");
        btnSoLonNhat.setName(""); // NOI18N
        btnSoLonNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoLonNhatActionPerformed(evt);
            }
        });

        jButton2.setText("Sổ nhỏ nhất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSoLonNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSoLonNhat)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoLonNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoLonNhatActionPerformed
        double a = 0,b = 0,c = 0;
        try
        {
            a = Double.parseDouble(txt1.getText());
            b = Double.parseDouble(txt2.getText());
            c = Double.parseDouble(txt3.getText());
        }
        catch(NumberFormatException e)
        {
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(this, "Bạn phải nhập đủ 3 số");
            return;
        }
        if(a == b && a == c)
        {
            txt1.setBackground(Color.yellow);
            txt2.setBackground(Color.yellow);
            txt3.setBackground(Color.yellow);
            return;
        }
        
        double max = a > b ? a : b;
        max = max > c ? max : c;
        
        if(a == max)
        {
            txt1.setBackground(Color.red);
            if(a == b)
                txt2.setBackground(Color.red);
            else if(a == c)
                txt3.setBackground(Color.red);
        }
        else if(b == max)
        {
            txt2.setBackground(Color.red);
            if(b == a)
                txt1.setBackground(Color.red);
            else if(b == c)
                txt3.setBackground(Color.red);
        }
        else
        {
            txt3.setBackground(Color.red);
            if(c == b)
                txt2.setBackground(Color.red);
            else if(c == a)
                txt1.setBackground(Color.red);
        }
    }//GEN-LAST:event_btnSoLonNhatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double a = 0,b = 0,c = 0;
        try
        {
            a = Double.parseDouble(txt1.getText());
            b = Double.parseDouble(txt2.getText());
            c = Double.parseDouble(txt3.getText());
        }
        catch(NumberFormatException e)
        {
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(this, "Bạn phải nhập đủ 3 số");
            return;
        }
        if(a == b && a == c)
        {
            txt1.setBackground(Color.yellow);
            txt2.setBackground(Color.yellow);
            txt3.setBackground(Color.yellow);
            return;
        }
        
        double min = a < b ? a : b;
        min = min < c ? min : c;
        
        if(a == min)
        {
            txt1.setBackground(Color.blue);
            if(a == b)
                txt2.setBackground(Color.blue);
            else if(a == c)
                txt3.setBackground(Color.blue);
        }
        else if(b == min)
        {
            txt2.setBackground(Color.blue);
            if(b == a)
                txt1.setBackground(Color.blue);
            else if(b == c)
                txt3.setBackground(Color.blue);
        }
        else
        {
            txt3.setBackground(Color.blue);
            if(c == b)
                txt2.setBackground(Color.blue);
            else if(c == a)
                txt1.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giao_Dien_Tim_Max.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giao_Dien_Tim_Max.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giao_Dien_Tim_Max.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giao_Dien_Tim_Max.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giao_Dien_Tim_Max().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSoLonNhat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}
